language: python
python:
 - "3.6.9"
before_script:
 - touch local_settings.py
 - echo METOFFICE_CLIENT_ID=\"abcd\" >> local_settings.py
 - echo METOFFICE_CLIENT_SECRET=\"abcd\" >> local_settings.py
 - echo STRAVA_CLIENT_ID=\"1234\" >> local_settings.py
 - echo STRAVA_CLIENT_SECRET=\"abcd\" >> local_settings.py
 - echo TOKEN_RESPONSE=\"abcd\" >> local_settings.py
 - echo DEFAULT_MINIMUM_SCORE=0 >> local_settings.py
install:
 - pip install -r requirements.txt
script:
 - pytest