language: python
python:
 - "3.6.9"
before_script:
 - touch local_settings.py
 - echo METOFFICE_CLIENT_ID="1234" >> local_settings.py
 - echo METOFFICE_CLIENT_SECRET="1234" >> local_settings.py
 - echo STRAVA_CLIENT_ID="1234" >> local_settings.py
 - echo STRAVA_CLIENT_SECRET="1234" >> local_settings.py
 - echo TOKEN_RESPONSE="1234" >> local_settings.py
install:
 - pip install -r requirements.txt
script:
 - pytest